### ISSUE TITLE
Backports to 0.5.x

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#1016]
**NOTE:** leave open and edit freely for as long as the v0.5.x branch is supported (i.e. not superseded by v0.6.x)

The following PRs could be backported to the 0.5.x branch:

- [x] remove kwargs from hybrid_forward input name inference (#846) 
- [x] Fix the quantiles used to compute MSIS (#849) 
- [x] Fix to_time_series_item in splitter (#874)
- [x] updated Pandas deprecation (#875)
- [x] Updated Frequency String for Pandas Timestamp (#884)
- [x] splitting features and uses DataEntry instead of TimeSeriesItem (#890)
- [x] fix multiprocessing in backtest function (#915)
- [x] Fix LDS distribution for the case where sequence_length==1 (#921) 
- [x] Defaulting MSIS to NaN when it can't be calculated. (#923) 
- [ ] ~Scale the negative binomial's gamma() #909~ (this would probably break existing models)
